from typing import List
from pydantic import BaseModel, Field
#base model is used for data validation and settings management using python type annotations
#field is used to provide extra information about model attributes

class Source(BaseModel):
    """schema for a source used by the agent"""
    url: str =Field(description="The URL of the source")

#default_factory is used to provide a default value for the field, in this case, an empty string

class AgentResponse(BaseModel):
    """schema for the agent's response"""
    answer: str=Field(description="The final answer generated by the agent")
    sources: List[Source]=Field(
        default_factory=list,
        description="List of sources used to generate the answer"
        )
    


